import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms & Conditions",
  description: "Terms and conditions for downloading and using Nexora Git.",
  alternates: { canonical: "/terms" },
};

const source = "https://github.com/Gh0stDeveloper/Nexora-Git";

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-4xl px-4 py-12 sm:px-6 lg:px-8">
      <div className="mb-8 border-b border-[#30363d] pb-6">
        <p className="mb-2 text-sm font-semibold text-[#58a6ff]">Nexora Git</p>
        <h1 className="text-3xl font-bold tracking-tight">Terms & Conditions</h1>
        <p className="mt-3 text-sm text-[#8b949e]">Last updated: October 7, 2026</p>
      </div>

      <div className="space-y-8 text-[15px] leading-7 text-[#c9d1d9]">
        <section>
          <h2 className="mb-2 text-xl font-semibold text-[#f0f6fc]">1. Scope</h2>
          <p>
            These terms apply to this Nexora Git download website and to APK files distributed directly through it.
            Nexora Git itself is open-source software; its source-code license remains the authoritative license for the software.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-xl font-semibold text-[#f0f6fc]">2. Open-source license</h2>
          <p>
            Nexora Git is distributed under the Apache License 2.0. Nothing on this website replaces, narrows or expands the rights and obligations granted by that license.
            Review the complete license in the{" "}
            <a className="text-[#58a6ff] hover:underline" href={`${source}/blob/main/LICENSE`} target="_blank" rel="noreferrer">source repository</a>.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-xl font-semibold text-[#f0f6fc]">3. APK downloads and updates</h2>
          <p>
            APK files offered here are generated by the project&apos;s self-hosted build pipeline and signed with the project&apos;s persistent Android signing identity.
            You are responsible for confirming that your device, Android version and security policy permit installation from outside an app store.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-xl font-semibold text-[#f0f6fc]">4. GitHub services</h2>
          <p>
            Nexora Git integrates with GitHub using GitHub&apos;s APIs and authorization flow. Your use of GitHub remains subject to GitHub&apos;s own terms, policies and account rules.
            Nexora Git is an independent project and is not affiliated with or endorsed by GitHub, Inc.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-xl font-semibold text-[#f0f6fc]">5. No warranty</h2>
          <p>
            To the extent permitted by the Apache License 2.0 and applicable law, the software and website are provided on an &quot;AS IS&quot; basis without warranties or conditions of any kind.
            Review source code, release hashes and security documentation before relying on the software for critical workflows.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-xl font-semibold text-[#f0f6fc]">6. Acceptable use</h2>
          <p>
            Do not use this website, its download infrastructure or the project&apos;s services to interfere with availability, bypass access controls, distribute malicious modifications as official builds, or impersonate the Nexora Git project.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-xl font-semibold text-[#f0f6fc]">7. Privacy</h2>
          <p>
            This download site is designed without advertising or behavioral analytics. Normal server and reverse-proxy logs may contain technical request information needed for security, diagnostics and service operation.
          </p>
        </section>

        <section>
          <h2 className="mb-2 text-xl font-semibold text-[#f0f6fc]">8. Changes</h2>
          <p>
            The project may update this website, release process and these terms as the software evolves. Material changes are versioned in the public source repository.
          </p>
        </section>
      </div>

      <div className="mt-10 rounded-lg border border-[#30363d] bg-[#161b22] p-5 text-sm text-[#8b949e]">
        For source, contribution rules and security reporting, visit{" "}
        <a className="font-semibold text-[#58a6ff] hover:underline" href={source} target="_blank" rel="noreferrer">Gh0stDeveloper/Nexora-Git</a>.
      </div>
    </main>
  );
}
