package com.nexora.git.core.repository

import com.nexora.git.core.database.GitHubRepositoryEntity

internal fun GitHubRepositoryEntity.toDomain(): RepositorySummary =
    RepositorySummary(
        id = repositoryId,
        nodeId = nodeId,
        name = name,
        fullName = fullName,
        ownerLogin = ownerLogin,
        ownerAvatarUrl = ownerAvatarUrl,
        description = description,
        privateRepository = privateRepository,
        fork = fork,
        archived = archived,
        visibility = visibility,
        language = language,
        defaultBranch = defaultBranch,
        cloneUrl = cloneUrl,
        htmlUrl = htmlUrl,
        stars = stars,
        forks = forks,
        openIssues = openIssues,
        sizeKb = sizeKb,
        updatedAt = updatedAt,
        pushedAt = pushedAt,
        permissions = RepositoryPermissions(
            admin = permissionAdmin,
            maintain = permissionMaintain,
            push = permissionPush,
            triage = permissionTriage,
            pull = permissionPull,
        ),
    )

internal fun RepositorySummary.toEntity(
    accountId: Long,
    cachedAtEpochMillis: Long,
): GitHubRepositoryEntity = GitHubRepositoryEntity(
    accountId = accountId,
    repositoryId = id,
    nodeId = nodeId,
    name = name,
    fullName = fullName,
    ownerLogin = ownerLogin,
    ownerAvatarUrl = ownerAvatarUrl,
    description = description,
    privateRepository = privateRepository,
    fork = fork,
    archived = archived,
    visibility = visibility,
    language = language,
    defaultBranch = defaultBranch,
    cloneUrl = cloneUrl,
    htmlUrl = htmlUrl,
    stars = stars,
    forks = forks,
    openIssues = openIssues,
    sizeKb = sizeKb,
    updatedAt = updatedAt,
    pushedAt = pushedAt,
    permissionAdmin = permissions.admin,
    permissionMaintain = permissions.maintain,
    permissionPush = permissions.push,
    permissionTriage = permissions.triage,
    permissionPull = permissions.pull,
    cachedAtEpochMillis = cachedAtEpochMillis,
)
